language: python

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - sqlite3
      - libsqlite3-dev

install:
  - 'pip install -r requirements.txt'
  - 'pip install -r tests-requirements.txt'

script:
  - 'flake8 --ignore=F403 .'
  - 'py.tests --cov=card_table tests/'

matrix:
  include:
    # TODO disbled due to use of enum - python: '2.7'
    - python: '3.5'
    - python: '3.6'

notifications:
  email: false

git:
  depth: 3

sudo: false
